JCTBankApp/YazilimBakimi-JCT-M/JCTBank.WebApp/Controllers/CreditController.cs
using JCTBank.BLL.Abstract;
using JCTBank.BLL.Concrete;
using JCTBank.DAL.Concrete.EfRepository;
using JCTBank.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JCTBank.WebApp.Controllers
{
    [Authorize]
    public class CreditController : Controller
    {
        ICreditService _creditService = new CreditManager(new EfRepositoryCreditDal());

        // GET: Credit
        public ActionResult CreditTransactions()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreditTransactions(Credit model)
        {
            if (ModelState.IsValid)
            {
                _creditService.Create(model);
                return RedirectToAction("ListAccount", "Account");
            }
            else
            {
                return RedirectToAction("ListAccount", "Account");
            }
        }
    }
}

JCTBankApp/YazilimBakimi-JCT-M/JCTBank.WebApp/Views/Credit/CreditTransactions.cshtml
@model JCTBank.Entity.Credit

@{
    ViewBag.Title = "CreditTransactions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-12">
    <section class="panel">
        <header class="panel-heading">

            <h4>Credit Transactions</h4>
        </header>
        <div class="panel-body">

            <form action="@Url.Action("CreditTransactions", "Credit")" method="post" enctype="multipart/form-data">
                <div class="form-horizontal">
                    <h4>Credit Transactions</h4>
                    <hr />
                    <div class="form-group">
                        <label class="control-label col-md-3" for="age">Age</label>
                        <div class="col-md-9">
                            <input type="number" class="form-control" name="age" id="age" placeholder="Age">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3" for="hashouse">House Condition</label>
                        <div class="col-md-9">
                            <select class="form-control" id="hashouse" name="hashouse">
                                <option value="true">Host</option>
                                <option value="false">Tenant</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3" for="creditsobtained">Credits Obtained</label>
                        <div class="col-md-9">
                            <input type="number" class="form-control" name="UsedCredits" id="UsedCredits">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3" for="hasphone">Phone Condition</label>
                        <div class="col-md-9">
                            <select class="form-control" id="hasphone" name="hasphone">
                                <option value="true">Var</option>
                                <option value="false">Yok</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Credit Calculation" class="btn btn-success" />
                    </div>
                </div>

            </form>
        </div>
    </section>
</div>