JCTBankApp/YazilimBakimi-JCT-M/JCTBank.WebApp/Controllers/CustomerController.cs
using JCTBank.BLL.Abstract;
using JCTBank.BLL.Concrete;
using JCTBank.DAL.Concrete.EfRepository;
using JCTBank.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JCTBank.WebApp.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        ICustomerService _customerService = new CustomerManager(new EfRepositoryCustomerDal());
        // GET: Customer

        public ActionResult ShowProfile()
        {
            Customer loginCustomer = Session["LoginUser"] as Customer;
            string LoginTCKN = Session["LoginUser"].ToString();

            var result = _customerService.GetByTCKN(LoginTCKN);
            if (result == null)
            {
                return View();

            }
            var profileCustomer = _customerService.GetAll().Where(x => x.CustomerNo == result.CustomerNo).ToList();

            return View(profileCustomer);
        }

        public ActionResult UpdateCustomer(int Id)
        {
            var result = _customerService.GetById(Id);
            return View("UpdateCustomer",result);
        }

        [HttpPost]
        public ActionResult UpdateCustomer(Customer model)
        {
            try
            {
                string LoginTCKN = Session["LoginUser"].ToString();
                var result = _customerService.GetByTCKN(LoginTCKN);
                model.TCKN = result.TCKN;
                model.CustomerNo = result.CustomerNo;
                result.Name = model.Name;
                result.Surname = model.Surname;
                result.TCKN = model.TCKN;
                result.CustomerNo = model.CustomerNo;
                result.IsDelete = false;
                result.Id = result.Id;
                result.PhoneNo = model.PhoneNo;
                result.Address = model.Address;
                result.Email = model.Email;
                result.Password = model.Password;
                result.RePassword = model.RePassword;
                _customerService.Update(model);
                return RedirectToAction("ShowProfile");

            }
            catch (Exception error)
            {
                ModelState.AddModelError("", error.Message);
                return View("UpdateCustomer", model);
            }
        }
    }
}

JCTBankApp/YazilimBakimi-JCT-M/JCTBank.WebApp/Views/Customer/ShowProfile.cshtml
@model List<JCTBank.Entity.Customer>


@{
    ViewBag.Title = "Profilim";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="col-lg-12">
    <section class="panel">
        <header class="panel-heading">

            <h4>My Profile</h4>
        </header>
        <div class="panel-body">

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Surname</th>
                        <th scope="col">Email</th>
                        <th scope="col">Phone Number</th>
                        <th scope="col">Address</th>
                        <th scope="col">Update</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Surname</td>
                            <td>@item.Email</td>
                            <td>@item.PhoneNo</td>
                            <td>@item.Address</td>
                            <td>
                                <a href="/Customer/UpdateCustomer/@item.Id" class="btn btn-primary btn-xs ">Update</a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>

        </div>
    </section>
</div>

JCTBankApp/YazilimBakimi-JCT-M/JCTBank.WebApp/Views/Customer/UpdateCustomer.cshtml
@using JCTBank.Entity
@model  Customer

@{
    ViewBag.Title = "UpdateCustomer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-lg-12">
    <section class="panel">
        <header class="panel-heading">

            <h4>Profile Settings</h4>
        </header>
        <div class="panel-body">
            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
            <p id="profile-name" class="profile-name-card"></p>
            @using (Html.BeginForm("UpdateCustomer", "Customer", FormMethod.Post, new { @id = "frmUpdateCustomer" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Name" , @pattern = "[A-Za-z]{1,32}"})
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Surname, new { @class = "form-control", @placeholder = "Surname" , @pattern = "[A-Za-z]{1,32}"})
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.PhoneNo, new { @class = "form-control", @placeholder = "PhoneNo", @onkeypress = "return event.charCode >=48 && event.charCode <=57"  })
                            @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "Email", @pattern = "[^ @]+@[^ @]+.[a-z]+"  })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control", @placeholder = "Address" })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.PasswordFor(model => model.Password, new { @class = "form-control", @placeholder = "Password" })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.RePassword, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.PasswordFor(model => model.RePassword, new { @class = "form-control", @placeholder = "RePassword" })
                            @Html.ValidationMessageFor(model => model.RePassword, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Güncelle" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
            <div>
                @Html.ActionLink("Return Profile", "ShowProfile")
            </div>
        </div>
    </section>
</div>